name: ChatPolls
version: 1.21
description: Generate simple chat polls for Minecraft servers.
api-version: 1.15
author: 3xpl0itz
main: com.expl0itz.chatpolls.MainChatPolls
commands:
    chpversion:
        description: Displays ChatPolls's current version.
        aliases: [chatpollsversion]
        usage: /chpversion
        permission: chatpolls.chpversion
        permission-message: §4You do not have permission to run this command.
    chpstart:
        description: Starts a poll.
        aliases: [chatpollsstart]
        usage: /chpstart -t <title> -d <description> -o <option1> -o <option2> (-delay <timeInSeconds>) (-r) (-a) (-clearchat)...
        permission: chatpolls.chpstart
        permission-message: §4You do not have permission to run this command.
    chpvote:
        description: Votes on an active poll.
        aliases: [chatpollsvote]
        usage: /chpvote <pollNumber> <optionNumber>
        permission: chatpolls.chpvote
        permission-message: §4You do not have permission to run this command.
    chplist:
        description: Lists all active polls.
        aliases: [chatpollslist]
        usage: /chplist
        permission: chatpolls.chplist
        permission-message: §4You do not have permission to run this command.
    chpinfo:
        description: Gets information on an active poll.
        aliases: [chatpollsinfo]
        usage: /chpinfo <pollNumber>
        permission: chatpolls.chpinfo
        permission-message: §4You do not have permission to run this command.
    chpmodify:
        description: Modifies an active poll.
        aliases: [chatpollsmodify]
        usage: /chpmodify <pollNumber>
        permission: chatpolls.chpmodify
        permission-message: §4You do not have permission to run this command.
    chpfinish:
        description: Ends an active poll.
        aliases: [chatpollsfinish]
        usage: /chpfinish <pollNumber>
        permission: chatpolls.chpfinish
        permission-message: §4You do not have permission to run this command.
    chptest:
        description: Tests a poll by sending it just to the sender.
        aliases: [chatpollstest]
        usage: /chptest -t <title> -d <description> -o <option1> -o <option2> (-delay <timeInSeconds>) (-a) (-clearchat)...
        permission: chatpolls.chptest
        permission-message: §4You do not have permission to run this command.
    chpreload:
        description: Reloads ChatPolls's configuration files.
        aliases: [chatpollsreload]
        usage: /chpreload
        permission: chatpolls.chpreload
        permission-message: §4You do not have permission to run this command.
permissions:
    chatpolls.*:
        description: Gives access to all ChatPolls commands.
        children:
            chatpolls.chpversion: true
            chatpolls.chpstart: true
            chatpolls.chpvote: true
            chatpolls.chplist: true
            chatpolls.chpinfo: true
            chatpolls.chpfinish: true
            chatpolls.chpreload: true
            chatpolls.chpmodify: true
            chatpolls.chptest: true
        default: op
    chatpolls.chpversion:
        description: Displays ChatPolls's current version.
        default: true        
    chatpolls.chpstart:
        description: Starts a poll.
        default: op
    chatpolls.chpvote:
        description: Votes on an active poll.
        default: true
    chatpolls.chplist:
        description: Lists all active polls.
        default: true
    chatpolls.chpinfo:
        description: Gets information on an active poll.
        default: true
    chatpolls.chpmodify:
        description: Modifies an active poll.
        default: op
    chatpolls.chpfinish:
        description: Ends an active poll.
        default: op
    chatpolls.chpreload:
        description: Reloads ChatPolls's configuration files.
        default: op
    chatpolls.chptest:
        description: Tests a poll by sending it just to the sender.
        default: true
    
